CREATE TABLE USERS (
    ID NUMBER(19, 0) NOT NULL,
    NAME VARCHAR2(255) NOT NULL,
    EMAIL VARCHAR2(255) NOT NULL,
    EMAIL_VERIFIED_AT TIMESTAMP NULL,
    "PASSWORD" VARCHAR2(255) NOT NULL,
    REMEMBER_TOKEN VARCHAR2(100) NULL,
    CREATED_AT TIMESTAMP NULL,
    UPDATED_AT TIMESTAMP NULL,
    CONSTRAINT USERS_ID_PK PRIMARY KEY ( ID )
) ALTER TABLE USERS ADD CONSTRAINT USERS_EMAIL_UK UNIQUE (
    EMAIL
) CREATE SEQUENCE USERS_ID_SEQ MINVALUE 1 START WITH 1 INCREMENT BY 1 CREATE TRIGGER USERS_ID_TRG BEFORE INSERT ON USERS FOR EACH ROW BEGIN IF :NEW.ID IS NULL THEN
    SELECT
        USERS_ID_SEQ.NEXTVAL INTO :NEW.ID
    FROM
        DUAL;

END IF;

END;

CREATE TABLE PASSWORD_RESET_TOKENS (
    EMAIL VARCHAR2(255) NOT NULL,
    TOKEN VARCHAR2(255) NOT NULL,
    CREATED_AT TIMESTAMP NULL,
    CONSTRAINT PASSWORD_RESET_TOKENS_EMAIL_PK PRIMARY KEY ( EMAIL )
) CREATE TABLE FAILED_JOBS (
    ID NUMBER(19, 0) NOT NULL,
    UUID VARCHAR2(255) NOT NULL,
    CONNECTION CLOB NOT NULL,
    "QUEUE" CLOB NOT NULL,
    PAYLOAD CLOB NOT NULL,
    EXCEPTION CLOB NOT NULL,
    FAILED_AT TIMESTAMP NOT NULL,
    CONSTRAINT FAILED_JOBS_ID_PK PRIMARY KEY ( ID )
) ALTER TABLE FAILED_JOBS ADD CONSTRAINT FAILED_JOBS_UUID_UK UNIQUE (
    UUID
) CREATE SEQUENCE FAILED_JOBS_ID_SEQ MINVALUE 1 START WITH 1 INCREMENT BY 1 CREATE TRIGGER FAILED_JOBS_ID_TRG BEFORE INSERT ON FAILED_JOBS FOR EACH ROW BEGIN IF :NEW.ID IS NULL THEN
    SELECT
        FAILED_JOBS_ID_SEQ.NEXTVAL INTO :NEW.ID
    FROM
        DUAL;

END IF;

END;

CREATE TABLE PERSONAL_ACCESS_TOKENS (
    ID NUMBER(19, 0) NOT NULL,
    TOKENABLE_TYPE VARCHAR2(255) NOT NULL,
    TOKENABLE_ID NUMBER(19, 0) NOT NULL,
    NAME VARCHAR2(255) NOT NULL,
    TOKEN VARCHAR2(64) NOT NULL,
    ABILITIES CLOB NULL,
    LAST_USED_AT TIMESTAMP NULL,
    EXPIRES_AT TIMESTAMP NULL,
    CREATED_AT TIMESTAMP NULL,
    UPDATED_AT TIMESTAMP NULL,
    CONSTRAINT PERSONAL_ACCESS_TOKENS_ID_PK PRIMARY KEY ( ID )
) CREATE INDEX PER_AC_TO_TOKE_TY_TOKE_ID_IN ON PERSONAL_ACCESS_TOKENS (
    TOKENABLE_TYPE,
    TOKENABLE_ID
) ALTER TABLE PERSONAL_ACCESS_TOKENS ADD CONSTRAINT PERSONA_ACCES_TOKEN_TOKE_UK UNIQUE (
    TOKEN
) CREATE SEQUENCE PERSONAL_ACCESS_TOKENS_ID_SEQ MINVALUE 1 START WITH 1 INCREMENT BY 1 CREATE TRIGGER PERSONAL_ACCESS_TOKENS_ID_TRG BEFORE INSERT ON PERSONAL_ACCESS_TOKENS FOR EACH ROW BEGIN IF :NEW.ID IS NULL THEN
    SELECT
        PERSONAL_ACCESS_TOKENS_ID_SEQ.NEXTVAL INTO :NEW.ID
    FROM
        DUAL;

END IF;

END;