ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

REVOKE ALL PRIVILEGES ON LOGMNR_SESSION_EVOLVE$ FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNR_GLOBAL$ FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNR_PDB_INFO$ FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNR_DID$ FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNR_UID$ FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNRGGC_GTLO FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNRGGC_GTCS FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNRC_DBNAME_UID_MAP FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNR_LOG$ FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNR_PROCESSED_LOG$ FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNR_SPILL$ FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNR_AGE_SPILL$ FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNR_RESTART_CKPT_TXINFO$ FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNR_ERROR$ FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNR_RESTART_CKPT$ FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNR_FILTER$ FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNR_SESSION_ACTIONS$ FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNR_PARAMETER$ FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNR_SESSION$ FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNR_PROFILE_TABLE_STATS$ FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNR_PROFILE_PLSQL_STATS$ FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON REDO_DB FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON REDO_LOG FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON ROLLING$CONNECTIONS FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON ROLLING$DATABASES FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON ROLLING$DIRECTIVES FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON ROLLING$EVENTS FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON ROLLING$PARAMETERS FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON ROLLING$PLAN FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON ROLLING$STATISTICS FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON ROLLING$STATUS FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON MVIEW$_ADV_WORKLOAD FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON MVIEW$_ADV_BASETABLE FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON MVIEW$_ADV_SQLDEPEND FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON MVIEW$_ADV_PRETTY FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON MVIEW$_ADV_TEMP FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON MVIEW$_ADV_FILTER FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON MVIEW$_ADV_LOG FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON MVIEW$_ADV_FILTERINSTANCE FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON MVIEW$_ADV_LEVEL FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON MVIEW$_ADV_ROLLUP FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON MVIEW$_ADV_AJG FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON MVIEW$_ADV_FJG FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON MVIEW$_ADV_GC FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON MVIEW$_ADV_CLIQUE FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON MVIEW$_ADV_ELIGIBLE FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON MVIEW$_ADV_OUTPUT FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON MVIEW$_ADV_EXCEPTIONS FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON MVIEW$_ADV_PARAMETERS FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON MVIEW$_ADV_INFO FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON MVIEW$_ADV_JOURNAL FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON MVIEW$_ADV_PLAN FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON AQ$_QUEUE_TABLES FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON AQ$_KEY_SHARD_MAP FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON AQ$_QUEUES FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON AQ$_SCHEDULES FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON AQ$_INTERNET_AGENTS FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON AQ$_INTERNET_AGENT_PRIVS FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON SCHEDULER_PROGRAM_ARGS_TBL FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON SCHEDULER_JOB_ARGS_TBL FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGSTDBY$PARAMETERS FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGSTDBY$EVENTS FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGSTDBY$APPLY_MILESTONE FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGSTDBY$SCN FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGSTDBY$FLASHBACK_SCN FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGSTDBY$PLSQL FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGSTDBY$SKIP_TRANSACTION FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGSTDBY$SKIP FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGSTDBY$SKIP_SUPPORT FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGSTDBY$HISTORY FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGSTDBY$EDS_TABLES FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON REPL_VALID_COMPAT FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON REPL_SUPPORT_MATRIX FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON SQLPLUS_PRODUCT_PROFILE FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON HELP FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNR_GT_TAB_INCLUDE$ FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNR_GT_USER_INCLUDE$ FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNR_GT_XID_INCLUDE$ FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNRT_MDDL$ FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON OL$ FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON OL$HINTS FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON OL$NODES FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNR_DICTSTATE$ FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNRC_GTLO FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNRC_GTCS FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNRC_SEQ_GG FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNRC_CON_GG FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNRC_CONCOL_GG FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNRC_IND_GG FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNRC_INDCOL_GG FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNRC_SHARD_TS FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNRC_TSPART FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNRC_TS FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNRC_GSII FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNRC_GSBA FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNRC_USER FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNR_SEED$ FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNR_DICTIONARY$ FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNR_OBJ$ FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNR_TAB$ FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNR_COL$ FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNR_ATTRCOL$ FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNR_TS$ FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNR_IND$ FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNR_USER$ FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNR_TABPART$ FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNR_TABSUBPART$ FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNR_TABCOMPART$ FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNR_TYPE$ FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNR_COLTYPE$ FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNR_ATTRIBUTE$ FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNR_LOB$ FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNR_CON$ FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNR_CONTAINER$ FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNR_CDEF$ FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNR_CCOL$ FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNR_ICOL$ FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNR_LOBFRAG$ FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNR_INDPART$ FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNR_INDSUBPART$ FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNR_INDCOMPART$ FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNR_LOGMNR_BUILDLOG FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNR_NTAB$ FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNR_OPQTYPE$ FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNR_SUBCOLTYPE$ FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNR_KOPM$ FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNR_PROPS$ FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNR_ENC$ FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNR_REFCON$ FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNR_IDNSEQ$ FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNR_PARTOBJ$ FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNRP_CTAS_PART_MAP FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGMNR_SHARD_TS FROM COFINA_COF_CREDIT;

REVOKE ALL PRIVILEGES ON LOGSTDBY$APPLY_PROGRESS FROM COFINA_COF_CREDIT;

DROP USER COFINA_COF_CREDIT CASCADE;

exit;