-- #CRÉATION DE L'utilisateur et configuration:

ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

CREATE USER COFINA_COF_CREDIT IDENTIFIED BY Coftg2021;

GRANT ALL PRIVILEGES TO COFINA_COF_CREDIT;

-- CONNECT cofina_cof_credit/Coftg2021@localhost:1521/xe

-- SELECT
--     TABLE_NAME
-- FROM
--     USER_TABLES;

exit;