-- #CRÉATION DE L'utilisateur et configuration:

ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

DROP USER COFINA_COF_CREDIT;

CREATE USER COFINA_COF_CREDIT IDENTIFIED BY Coftg2021;

GRANT CREATE SESSION, CREATE TABLE TO COFINA_COF_CREDIT;

-- #GRANT SELECT, INSERT, UPDATE, DELETE TO COFINA_COF_CREDIT;

-- CONNECT cofina_cof_credit/Coftg2021@localhost:1522/xe

-- SELECT
--     TABLE_NAME
-- FROM
--     USER_TABLES;

CREATE OR REPLACE TRIGGER GRANT_PRIVILEGES AFTER CREATE ON SCHEMA
DECLARE
BEGIN
    EXECUTE IMMEDIATE 'GRANT INSERT, UPDATE, DELETE, SELECT ON COFINA_COF_CREDIT.'
                      || ORA_DICT_OBJ_NAME
                      || ' TO cofina_cof_credit';
    EXECUTE IMMEDIATE 'GRANT INSERT, UPDATE, DELETE, SELECT ON '
                      || ORA_DICT_OBJ_NAME
                      || ' TO system';
END;
/

exit;